build: off

# Attention: ICU > 59.1 does no longer support compilers older than VS 2015
image:
  - Visual Studio 2015
  - Visual Studio 2017

platform:
#  - x86
  - x64

configuration:
- Debug
- Release

environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"
    CYGWIN_ROOT: "C:\\cygwin64"

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan --upgrade
  - pip.exe install conan_package_tools
  - conan user # It creates the conan data directory

test_script:
  - python build.py
